#!/usr/bin/env python
import subprocess
import json
import sys
import os
import subprocess
import atexit


def _cleanup():
    _proc.terminate()


atexit.register(_cleanup)


def _error(msg):
    sys.stderr.write('{}\n'.format(msg))
    sys.exit(1)


try:
    with open('settings.json', 'rb') as f:
        settings = json.load(f)
except IOError:
    sys.exit('settings.json doesn\'t exist')
for k, v in settings.iteritems():
    os.environ[k] = v

_proc = subprocess.Popen(['./services/project-processor/project-processor.py', ])
try:
    subprocess.check_call(
        ['./node_modules/.bin/babel-node', '.', ])
except subprocess.CalledProcessError:
    _error('Node failed')
except KeyboardInterrupt:
    sys.exit(0)
