#!/usr/bin/env python3
import subprocess
import sys


def _error(msg):
    sys.stderr.write('{}\n'.format(msg))
    sys.exit(1)


try:
    subprocess.check_call([
        './node_modules/.bin/webpack-dev-server', '-d', '--inline',
        '--content-base', 'public',
    ])
except subprocess.CalledProcessError:
    _error('Webpack dev server failed')
except KeyboardInterrupt:
    sys.exit(0)
