FROM rethinkdb:2.3
MAINTAINER MuzHack Team <contact@muzhack.com>

WORKDIR /app
ENTRYPOINT ["python3", "backup-database.py"]

RUN \
  apt-get update && \
  apt-get install -y python3 python-pip3 python-pip && \
  rm -rf /var/lib/apt/lists/*

COPY ./ .
RUN pip3 install -r requirements.txt
RUN pip2 install gcs-oauth2-boto-plugin
